# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170328_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hf',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wf',
        ),
    ]
